application: election-maps
version: nh2012-test
runtime: python
api_version: 1

handlers:

- url: /(vote-data|.*\.html)
  script: results-app.py
  
- url: /(css/.*|images/.*|js/.*|shapes/.*)
  static_files: static/\1
  upload: static/(css/.*|images/.*|js/.*|shapes/.*)
