application: election-maps
version: nh2012-test
runtime: python
api_version: 1

handlers:

- url: /vote-data
  script: results-app.py
  
- url: /(.*\.html|.*\.xml|css/.*|images/.*|js/.*|shapes/.*)
  static_files: static/\1
  upload: static/(.*)
