application: election-maps
version: nh
runtime: python
api_version: 1

handlers:
  
- url: /(.*\.html|.*\.xml|css/.*|images/.*|js/.*|shapes/.*)
  static_files: static/\1
  upload: static/(.*)
